import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BannerCaraousal from "@/components/bannercarousel";
import Announcement from "@/components/announcement";


import { ApolloWrapper } from '../components/ApolloWrapper';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BHU Admission Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloWrapper>
          <Navbar></Navbar>
          <BannerCaraousal></BannerCaraousal>
         <Announcement> </Announcement >
        </ApolloWrapper>
        {children}
      </body>
    </html>
  );
}
